#-------------------------------
# General Site Settings
baseURL = "https://moyorun.com/"
languageCode = "ko-kr"
title = "모요런"
theme = "coderon"

[params]
  description = "코드와 러닝 사이, 40대 기획&개발자의 생각 저장소"
  mainSections = ["posts"]

#-------------------------------
# Color Scheme
[params.color_scheme]
  default = "dark"
  toggle = true

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "홈"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "러닝"
    url = "/categories/러닝/"
    weight = 2

  [[menu.main]]
    name = "일상"
    url = "/categories/일상/"
    weight = 3

  [[menu.main]]
    name = "정보"
    url = "/categories/정보/"
    weight = 4

  [[menu.main]]
    name = "보관함"
    url = "/archive/"
    weight = 5

  [[menu.main]]
    identifier = "more"
    name = "더보기"
    weight = 6

  [[menu.main]]
    name = "러닝 기록"
    url = "/running-history/"
    parent = "more"
    weight = 1

  [[menu.main]]
    name = "소개"
    url = "/about/"
    parent = "more"
    weight = 2

#-------------------------------
# Author Settings
[params.author]
  author_name = "모요!"
  author_avatar = "/images/profile.png"

#-------------------------------
# Hero Settings
[params.hero]
  enable = true
  hero_avatar = "/images/profile.png"
  hero_title = "모요런"
  hero_subtitle = "40대 달리기를 즐겨하는 기획&개발자"
  hero_description = "코드를 짜고, 아스팔트를 달리며, 생각을 정리합니다. 기획과 개발, 그리고 삶의 균형을 찾아가는 여정을 기록합니다."
  hero_image = "/images/hero.png"
  hero_image_caption = "중요한 건 기록이지. 기록 없으면 무슨 재미로 달리나"
  hero_button_text = "소개 보기"
  hero_button_link = "/about"

  # Marathon Personal Records
  [[params.hero.marathon_records]]
    distance = "10K"
    time = "00:45:56"
    event = "'24.11.17 부천 복사골 마라톤"

  [[params.hero.marathon_records]]
    distance = "Half"
    time = "01:40:55"
    event = "'25.09.28 인천 송도 국제마라톤"

  [[params.hero.marathon_records]]
    distance = "Full"
    time = "03:48:59"
    event = "'25.04.20 경기 마라톤"

#-------------------------------
# Blog Section
[params.blog]
  enable = true
  blog_title = "최근 글"

#-------------------------------
# Pagination
[pagination]
  pagerSize = 10

#-------------------------------
# Other Features (비활성화)
[params.logos]
  enable = false

[params.tags_section]
  enable = false

[params.videos]
  enable = false

[params.gallery]
  enable = false

[params.mailchimp]
  enable = false

[params.disqus]
  enable = false

[params.giscus]
  enable = true

#-------------------------------
# Footer Settings
[params.footer]
  footer_description = "코드와 러닝 사이, 40대 기획&개발자의 생각 저장소"

#-------------------------------
# Social Settings
[[params.social]]
  icon = "fa-brands fa-github"
  name = "Github"
  link = "https://github.com/heyoom"

[[params.social]]
  icon = "fa-solid fa-globe"
  name = "Website"
  link = "https://minorlab.com"

#-------------------------------
# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

#-------------------------------
# Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    ordered = true
    endLevel = 3

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false

#-------------------------------
# Output Formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
